### ISSUE TITLE
Visit Japan

### ISSUE THREAD

**Issue by feross** [feross/Life#1]
![mt-fuji-view](https://f.cloud.github.com/assets/121766/795230/b5fbc8ba-ecea-11e2-8c4b-500cf1b22ffc.jpg)

Things I like about Japan:
- Anime
- Japanese design
- Samurai
- Three-generation households
- Cherry blossoms
- Respectful, polite culture

**Comment by caxvis** [comment]
Indonesia? Anytime soon?
