### ISSUE TITLE
Visit the Aurora 

### ISSUE THREAD

**Issue by feross** [feross/Life#11]
Behold, the Northern Lights:

![aurora_kuenzli_big](https://f.cloud.github.com/assets/121766/794295/1ace6ff0-ec8b-11e2-95f1-778de92ca164.jpg)

For extra style points, rent an igloo hotel and sleep with a view of the aurora.

![hotel-kakslauttanen-igloo-village-lead-537x357](https://f.cloud.github.com/assets/121766/794296/1cdd4afa-ec8b-11e2-9743-939e3e7639af.jpg)

**Comment by feross** [comment]
I saw the Northern Lights at [Arctic JS](http://arcticjs.club/), the conference I helped to organize earlier this year :+1: 

Onward!

**Comment by AntouanK** [comment]
@feross Could you give us a summary of that visit?
I'm assuming this is the hotel ( http://www.kakslauttanen.fi/en/ ).

**Comment by feross** [comment]
@AntouanK I actually ended up going to Svalbard instead, and stayed in an Airbnb. https://github.com/adventure-js/arcticjs.club/issues/5
