### ISSUE TITLE
Make enough passive income that I don't need to get a job

### ISSUE THREAD

**Issue by feross** [feross/Life#19]

**Comment by Kikobeats** [comment]
How to? sound VERY interesting :octopus:

**Comment by tejasmanohar** [comment]
Curious _how_ you're doing so as well :P

**Comment by dideler** [comment]
@Kikobeats @tejasmanohar my guess is #3

**Comment by feross** [comment]
@dideler Yep, that's right.

I plan to do a talk some time next year with advice about making passive income online. I think it's something that a lot of programmers have the right skillset to do, and it's great for increasing your personal freedom.

**Comment by jorgeas80** [comment]
That sounds pretty cool. I've tried to learn about passive income online, but everything looks the same for me: more SEO stuff than dev stuff. 

And I have some ethical concerns about that. We're not doing anything "good", just tricking people to buy things or generate traffic to specific sites to generate money for them (and for us, in the same operation). 

So, am I missing anything? Is there a different path?

**Comment by feross** [comment]
> And I have some ethical concerns about that. We're not doing anything "good", just tricking people to buy things or generate traffic to specific sites to generate money for them (and for us, in the same operation).

This is a common misconception among developers, I think. I used to believe the same thing. But I don't think that spending a bit of time explaining your product and making it easy for people to discover and understand what it does is "tricking people". Doing a bit of marketing is not evil. If you don't explain your product or spend any time telling people about it, no customers will discover it and therefore no one will get the benefit of the great product that you've built.

I think once in a while there's a product that just sells itself with zero effort spent on marketing, but even then, I think you'll find that the creators did a good job of explaining what the product does.

As a concrete example, I've spent zero dollars on marketing Study Notes (other than a few hundred bucks spent to experiment with Facebook Ads, which didn't work) but it's number 1 on Google and gets millions of visitors per month.

I would say that I've spent time on marketing. But not the evil, nasty kind that you're probably thinking of.

**Comment by jorgeas80** [comment]
Ok, my point was lacking of deeper explanation. Fair enough. And you're totally right.

I DO believe marketing is necessary. You need to make people know about your product. If I did things right, I created the product for my users. I code for the people I'm trying to help, not just for me. And there is absolutely nothing unethical about that. That's the core of software industry, right? Create useful software for someone, and make that someone know about it by means of marketing.

My problem isn't with marketing itself, or with SEO. We need that. It's with some marketing techniques: 

- black hat SEO tricks
- make your logo/look&feel similar to that very well known one, to make people think they're buying a different product
- just copy content from another sites, make a cool landing page with some template and bring traffic to it
- buy followers/good reviews to make people think your product is greater that it may be
- etc

Ok, I know it's sometimes difficult to draw a line. But to summarize my thoughts on this topic: if you (the developer) spend more time looking for SEO/marketing stuff than coding the product, it will probably be smokeselling. Let the marketing people do their job, and you make yours.

Hope I made my point clearer now

**Comment by feross** [comment]
Yeah -- lots of marketing techniques are gross. I agree with you! But developers can be pretty gross too: check out some of the examples here: http://darkpatterns.org

I think the key is to just not do anything that makes you feel icky. Have some standards and lines you won't ever cross. And when possible, design your system to be decentralized so that you can't change it for the worse if you become evil someday! I talk about this idea a bit here: https://www.youtube.com/watch?v=hcbNdLDWCO8

**Comment by jorgeas80** [comment]
Yep, that's the key: you follow a code, and stick to it unless you prove it wrong, from ethical/practical point of view.

Thanks for the links. I'll already watching your talk :-)
